### ISSUE TITLE
Are we dead yet?

### ISSUE THREAD

**Issue by sergeevabc** [NickBusey/Workflowier#1]
Dear Nick, workflowier.com seems to be broken, last commit is dated back to spring (May), yet roadmap is full of planned but unreleased features. What do you think about that?

**Comment by NickBusey** [comment]
I was actually just writing some new features this evening. Not sure what you're asking about though? Feel free to implement anything and submit a pull request. Not sure why the GH pages domain went down, I'll take a look. Are you using the script, and hoping for the new features? If so, glad to hear people are making use of it.

**Comment by NickBusey** [comment]
The domain is back up now. Should be a new release fairly soon..

**Comment by NickBusey** [comment]
Just released version 0.1 with image previews. If there's a specific feature you're waiting on, let me know and I can move that up the priorities.
